name: tusharwadhwa.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73853
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8732564400415868
  lightness: 0.6755566394422203
  saturation: 0.4494456243701279
  rhythmicContrast: 0.45154524175450206
purpose: []
